-- SEQUÊNCIAS
CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_transferencia START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- TABELAS
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(255) NOT NULL,
    CPF_CNPJ VARCHAR2(18) UNIQUE NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    CARTEIRA NUMBER(10, 2) NOT NULL,
    IS_LOJISTA NUMBER(1) CHECK (IS_LOJISTA IN (0, 1)) NOT NULL
);

CREATE TABLE TRANSFERENCIA (
    ID_TRANSFERENCIA NUMBER PRIMARY KEY,
    TIPO_TRANSACAO VARCHAR2(25) NOT NULL,
    PAGADOR NUMBER NOT NULL,
    RECEBEDOR NUMBER NOT NULL,
    VALOR NUMBER(10, 2) NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    COMENTARIO VARCHAR2(255),
    CONSTRAINT fk_pagador FOREIGN KEY (PAGADOR) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_recebedor FOREIGN KEY (RECEBEDOR) REFERENCES USUARIO(ID_USUARIO)
);



