-- SEQUÊNCIAS
CREATE SEQUENCE seq_usuario START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_carteira START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- TABELAS
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(255) NOT NULL,
    CPF_CNPJ VARCHAR2(18) UNIQUE NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    IS_LOJISTA NUMBER(1) CHECK (IS_LOJISTA IN (0, 1)) NOT NULL
);

CREATE TABLE CARTEIRA (
    ID_CARTEIRA NUMBER PRIMARY KEY,
    VALOR NUMBER(10, 2) NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);


