-- Inserir 5 usuários comuns
INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'João Silva', '123.456.789-00', 'joao.silva@example.com', 'senha123', 0, 0.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Maria Oliveira', '987.654.321-00', 'maria.oliveira@example.com', 'senha123', 0, -100.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Carlos Souza', '456.789.123-00', 'carlos.souza@example.com', 'senha123', 0, 150.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Ana Costa', '789.123.456-00', 'ana.costa@example.com', 'senha123', 0, 200.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lucas Pereira', '321.654.987-00', 'lucas.pereira@example.com', 'senha123', 0, 800.00);

-- Inserir 5 lojistas
INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lojista A', '12.345.678/0001-99', 'lojistaA@example.com', 'senha123', 1, 0.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lojista B', '23.456.789/0001-88', 'lojistaB@example.com', 'senha123', 1, 120.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lojista C', '34.567.890/0001-77', 'lojistaC@example.com', 'senha123', 1, 500.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lojista D', '45.678.901/0001-66', 'lojistaD@example.com', 'senha123', 1, 0.00);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA, CARTEIRA)
VALUES (seq_usuario.NEXTVAL, 'Lojista E', '56.789.012/0001-55', 'lojistaE@example.com', 'senha123', 1, -50.00);