-- 5 usuários comuns
INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'João Silva', '123.456.789-00', 'joao.silva@example.com', 'senha123', 0);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Maria Oliveira', '987.654.321-00', 'maria.oliveira@example.com', 'senha123', 0);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Carlos Souza', '456.789.123-00', 'carlos.souza@example.com', 'senha123', 0);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Ana Costa', '789.123.456-00', 'ana.costa@example.com', 'senha123', 0);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lucas Pereira', '321.654.987-00', 'lucas.pereira@example.com', 'senha123', 0);

-- 5 lojistas
INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lojista A', '12.345.678/0001-99', 'lojistaA@example.com', 'senha123', 1);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lojista B', '23.456.789/0001-88', 'lojistaB@example.com', 'senha123', 1);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lojista C', '34.567.890/0001-77', 'lojistaC@example.com', 'senha123', 1);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lojista D', '45.678.901/0001-66', 'lojistaD@example.com', 'senha123', 1);

INSERT INTO USUARIO (ID_USUARIO, NOME_COMPLETO, CPF_CNPJ, EMAIL, SENHA, IS_LOJISTA)
VALUES (seq_usuario.NEXTVAL, 'Lojista E', '56.789.012/0001-55', 'lojistaE@example.com', 'senha123', 1);

-- Carteiras para os usuários
INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 00.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'João Silva'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, -100.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Maria Oliveira'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 150.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Carlos Souza'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 200.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Ana Costa'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 800.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lucas Pereira'));

-- Carteiras para os lojistas
INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 0.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lojista A'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 120.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lojista B'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 500.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lojista C'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, 0.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lojista D'));

INSERT INTO CARTEIRA (ID_CARTEIRA, VALOR, ID_USUARIO)
VALUES (seq_carteira.NEXTVAL, -50.0, (SELECT ID_USUARIO FROM USUARIO WHERE NOME_COMPLETO = 'Lojista E'));