CREATE SEQUENCE seq_transferencia START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TRANSFERENCIA (
    ID_TRANSFERENCIA NUMBER PRIMARY KEY,
    TIPO_TRANSACAO VARCHAR2(25) NOT NULL,
    PAGADOR NUMBER NOT NULL,
    RECEBEDOR NUMBER NOT NULL,
    VALOR NUMBER(10, 2) NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    COMENTARIO VARCHAR2(255),
    ID_CARTEIRA NUMBER NOT NULL,
    CONSTRAINT fk_pagador FOREIGN KEY (PAGADOR) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_recebedor FOREIGN KEY (RECEBEDOR) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_carteira FOREIGN KEY (ID_CARTEIRA) REFERENCES CARTEIRA(ID_CARTEIRA)
);

